name: awesome_snackbar_content
description: Uplift your snackbar experience with various alert messages i.e. success, failure, help or warning with unique UI design.
version: 0.1.5
homepage: https://github.com/mhmzdev/awesome_snackbar_content

environment:
  sdk: ">3.4.3"
  flutter: ">=1.17.0"

dependencies:
  flutter_svg: ^2.0.4

  flutter:
    sdk: flutter
    
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# The following section is specific to Flutter packages.
flutter:

  assets:
    - assets/
    - assets/types/